# Generated by Django 3.2.9 on 2022-04-09 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=1000, null=True)),
                ('types_of_bill', models.CharField(max_length=3000, null=True, verbose_name='Types your bill Information')),
                ('bill', models.CharField(max_length=2000, null=True)),
                ('total_amount', models.CharField(max_length=3000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
