# Generated by Django 3.2.9 on 2022-04-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdashboard',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantdashboard',
            name='flat_no',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='tenantdashboard',
            name='bill',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tenantdashboard',
            name='serial',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tenantdashboard',
            name='total_amount',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tenantdashboard',
            name='types_of_bill',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Types your bill Information'),
        ),
    ]
