# Generated by Django 3.2.9 on 2022-04-09 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_app', '0002_auto_20220409_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantdashboard',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tenantdashboard',
            name='flat_no',
        ),
        migrations.AlterField(
            model_name='tenantdashboard',
            name='bill',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tenantdashboard',
            name='types_of_bill',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.CreateModel(
            name='ApartmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(blank=True, max_length=5000, null=True)),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
