# Generated by Django 3.2.9 on 2022-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0005_user_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=400, null=True)),
                ('flat_name', models.CharField(blank=True, max_length=400, null=True)),
                ('cost', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
