# Generated by Django 3.2.9 on 2022-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0006_admin_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_dashboard',
            name='clerence',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
