# Generated by Django 3.2.9 on 2022-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0007_admin_dashboard_clerence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=500, null=True)),
                ('cost', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
