# Generated by Django 3.2.9 on 2022-04-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0008_parking_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_fees',
            name='status',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
